### ISSUE TITLE
More verbose lift logging

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pysensorproxy#44]
To debug the lift more efficiently, we should add more logs, as suggested by @gisma.

WiFi Status wer mit wem verbunden ist und natürlich nicht verbunden dazu die geglaubte Höhe//laufzeit
Logische Parameter jslubfahrt hoch runter mit Höhenangabe und normale messefahrt mit Höhenangabe

**Comment by gisma** [comment]
haha I will translate it for you: IMHO we need a highly detailed  logging dealing with:

- the Hall Sensor Status, we need all hall sensor signals and the corresponding altitude and time
- the WiFi status, we need a full protocol of all Wifi events. That means not only lost connections but also other detected Wifis etc. according to the event we need the information of altitude and time

**Comment by lampep** [comment]
with [https://github.com/Nature40/pysensorproxy/commit/9c392e186311e2c376f1622fe5d32d987c39f999](url) and [https://github.com/Nature40/pysensorproxy/commit/0dfa0cf2836fafc680978b0d3fcc276911eb91c2](url) I added some more debug output for the hall sensors. Additional I added the height to logs every time we move the lift. So the last height value in the logs have to be the current height. 
It's untested because of the attending of the LCN conference and not having hardware here. But it is only some output and I think it should work. Finger crossed. 
For Wifi and system state we want to store systemd logs for our services and the wpa_supplicant logs. Additional I added a wifi scan every time we switch from or to the ap mode. So we get a wifi scan result before and after every lift movement.
